def roman(num):
    list=[]
    i=0
    while(num>0):
        temp=num%10
        if(i==0):
            if(temp==1):
                list.append('I')
            if(temp==2):
                list.append('II')
            if(temp==3):
                list.append('III')
            if(temp==4):
                list.append('IV')
            if(temp==5):
                list.append('V')
            if(temp==6):
                list.append('VI')
            if(temp==7):
                list.append('VII')
            if(temp==8):
                list.append('VIII')
            if(temp==9):
                list.append('IX')
        elif(i==1):
            if(temp==1):
                list.append('X')
            if(temp==2):
                list.append('XX')
            if(temp==3):
                list.append('XXX')
            if(temp==4):
                list.append('XL')
            if(temp==5):
                list.append('L')
            if(temp==6):
                list.append('LX')
            if(temp==7):
                list.append('LXX')
            if(temp==8):
                list.append('LXXX')
            if(temp==9):
                list.append('XC')
        elif(i==2):
            if(temp==1):
                list.append('C')
            if(temp==2):
                list.append('CXX')
            if(temp==3):
                list.append('CXX')
            if(temp==4):
                list.append('CXL')
            if(temp==5):
                list.append('CL')
            if(temp==6):
                list.append('CLX')
            if(temp==7):
                list.append('CLXX')
            if(temp==8):
                list.append('CLXXX')
            if(temp==9):
                list.append('CM')
        elif(i==3):
            if(temp==1):
                list.append('M')
            if(temp==2):
                list.append('MM')
            if(temp==3):
                list.append('MMM')
            if(temp==4):
                list.append('MMMM')
        num//=10
        i+=1
    j=0
    str=''
    while(j<len(list)):
        str+=list[len(list)-j-1]
        j+=1
    return str
print(roman(150))
